### ISSUE TITLE
Swagger Page doesn't work for input

### ISSUE THREAD

**Issue by jpmorris** [GSA-TTS/FAC#1102]
The swagger page is currently down.  But more than that it's set to use HTTP but when you try and test with parameters the error returned says it's expecting HTTPS

https://fac-dev-swagger.app.cloud.gov/

**Comment by jadudm** [comment]
@asteel-gsa , I will try and get to this, but perhaps you will beat me to it.

I'd like to disable the "try it out" part of the Swagger interface, so that it serves only as a source of documentation. This thread in the swagger repo talks about this, and I think this comment has the solution:

https://github.com/swagger-api/swagger-ui/issues/3725#issuecomment-904724595

Whether we come back to this, and later add the "try it out" functionality back in, is TBD. However, leading up to MVP, I'd like to remove it as a surface for breakage and questions. Our docs support exploring the API via `curl`, and we may have some other tools in time.

I've tagged us both, but if it's something you're able to pick up as a quickie, I know I'd appreciate it.

**Comment by asteel-gsa** [comment]
@jadudm [Branch](https://github.com/GSA-TTS/FAC/tree/1102-swagger-page-doesnt-work-for-input)

```yaml
  swagger:
    image: swaggerapi/swagger-ui
    expose:
      - 8080
    ports:
      - 8029:8080
    links:
      - db
    environment:
      SUPPORTED_SUBMIT_METHODS: "[]"
```

`SUPPORTED_SUBMIT_METHODS: "[]"` has disabled "try it out". checkout the branch and `docker compose up` and then navigate to `http://localhost:8029/` and there will be no "try it out" button. Granted, it is a sample site, but yea.
![image](https://github.com/GSA-TTS/FAC/assets/130377221/5060a84b-fde4-4c98-99b7-60d87e04afaa)
