### ISSUE TITLE
Add regression tests to pull request checks

### ISSUE THREAD

**Issue by phildominguez-gsa** [GSA-TTS/FAC#2311]
### Tasks

```[tasklist]
- [ ] Modify `pull-request-checks.yml` to run the tests for PRs after a commit (see code below)
- [ ] Ensure dev env vars are set
```

The code for `pull-request-checks.yml`:
```
regression-tests:
    uses: ./.github/workflows/regression-tests.yml
    secrets: inherit
    with:
      url: "https://fac-dev.app.cloud.gov/"
      environment: "dev"
```
